import { StyleSheet } from 'react-native';
import { SPACING } from './constants';

export const COLORS = {
  background: '#FFF9F3',
  card: '#FFFFFF',
  ink: '#131A26',
  muted: '#6B7280',
  primary: '#FF7A1A',
  primaryDark: '#EA580C',
  softOrange: '#FFF1E3',
  line: '#F3E7D8',
  dotIdle: '#EADDCB',
  badge: '#4ADE80',
  textSecondary: '#374151',
  blobTop: '#FFE7CF',
} as const;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  decoration: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  blobTop: {
    position: 'absolute',
    top: -110,
    right: -90,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: COLORS.blobTop,
    opacity: 0.7,
  },
  blobBottom: {
    position: 'absolute',
    bottom: -120,
    left: -100,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: COLORS.softOrange,
  },
  list: {
    flex: 1,
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.screen,
    paddingBottom: 8,
  },
  logo: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.ink,
    letterSpacing: -0.5,
  },
  logoAccent: {
    color: COLORS.primary,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  counter: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.muted,
    fontVariant: ['tabular-nums'],
  },
  skipButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: SPACING.radiusPill,
    backgroundColor: 'rgba(19, 26, 38, 0.06)',
  },
  skipText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },

  slide: {
    alignItems: 'center',
    paddingHorizontal: SPACING.screen,
  },
  imageCard: {
    height: 380,
    maxHeight: 420,
    borderRadius: SPACING.radiusCard,
    overflow: 'hidden',
    backgroundColor: COLORS.card,
    borderWidth: 4,
    borderColor: COLORS.card,
    shadowColor: COLORS.primaryDark,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.16,
    shadowRadius: 28,
    elevation: 8,
  },
  image: {
    width: '100%',
    height: '100%',
  },
  badgeOnImage: {
    position: 'absolute',
    top: 14,
    left: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: SPACING.radiusPill,
    backgroundColor: 'rgba(19, 26, 38, 0.72)',
  },
  badgeDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: COLORS.badge,
  },
  badgeOnImageText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.card,
    letterSpacing: 0.2,
  },
  textBlock: {
    alignItems: 'center',
    marginTop: 24,
    paddingHorizontal: 4,
  },
  stepPill: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: COLORS.primaryDark,
    backgroundColor: COLORS.softOrange,
    borderWidth: 1,
    borderColor: COLORS.line,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: SPACING.radiusPill,
    overflow: 'hidden',
    marginBottom: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.5,
    lineHeight: 34,
    textAlign: 'center',
    color: COLORS.ink,
    marginBottom: 10,
  },
  description: {
    fontSize: 15,
    lineHeight: 24,
    textAlign: 'center',
    color: COLORS.muted,
    maxWidth: 320,
  },

  footer: {
    paddingHorizontal: SPACING.screen,
    paddingTop: 8,
  },
  dotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 20,
    marginBottom: 16,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.dotIdle,
  },
  dotActive: {
    width: 32,
    backgroundColor: COLORS.primary,
  },
  primaryButton: {
    height: 58,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: SPACING.radiusButton,
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.32,
    shadowRadius: 16,
    elevation: 6,
  },
  primaryButtonText: {
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.2,
    color: COLORS.card,
  },
});
